# prometheus.yml
global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"

scrape_configs:
  - job_name: "nodejs-api"
    static_configs:
      - targets: ["dms_api:3000"]
    metrics_path: "/metrics"
    scrape_interval: 5s
    scrape_timeout: 5s

  - job_name: "prometheus"
    static_configs:
      - targets: ["dms_prometheus:9090"]
